name: ecodata-client-plugin build

on:
  push:
    branches:
      - dev
      - master
      - feature/**
      - hotfix/**
      - release/**

env:
  TZ: Australia/Canberra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'AtlasOfLivingAustralia'

      - run: npm install
      - run: npm run package-turf


      - name: Update your package.json with an npm pre-release version
        id: pre-release-version
        uses: adobe/update-prerelease-npm-version@4dea8f295023f5b18126afd79bae1057a5b92d6e #v1.2.0

      - run: npm publish --tag=snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Check chromedriver is available
        run: echo $CHROMEWEBDRIVER

      - name: Check chromedriver version
        run: $CHROMEWEBDRIVER/chromedriver --version

      - name: Clean to remove clover instrumentation
        run: ./gradlew clean

      - name: Run tests and jacoco coverage report with Gradle
        run: ./gradlew -PenableJacoco=true -Dwebdriver.chrome.driver=$CHROMEWEBDRIVER/chromedriver check

      - name: Run javascript unit tests
        run: npm run test

      - name: Clean to remove clover instrumentation
        run: ./gradlew clean

      - name: Publish the JAR to the repository
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
