name: ecodata-client-plugin build

on:
  push:
    branches:
      - dev
      - master
      - feature/**
      - hotfix/**

env:
  TZ: Australia/Canberra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run package-turf
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: run _Events target
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: _Events

#      - name: Run tests and jacoco coverage report with Gradle
#        uses: gradle/gradle-build-action@v2.4.2
#        with:
#          arguments: -PenableJacoco=true check

      - name: Run javascript unit tests
        run: node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless

      - name: Clean to remove clover instrumentation
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean

      - name: Publish the JAR to the repository
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
