---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: ecodata.client.plugin
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    jmx:
        enabled: true
        unique-names: true
    devtools:
        livereload:
            enabled: true
# Spring Actuator Endpoints are Disabled by Default

disableCAS: true


management:
    endpoints:
        enabled-by-default: false

lists.baseURL : https://lists-ws.test.ala.org.au/

app:
    http:
        header:
            hostName: "X-ALA-hostname"
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

userProfile:
    userIdAttribute: "username"

---
environments:
    test:
        security:
            cas:
                appServerName: 'n/a'
            oidc:
                enabled: true
                discoveryUri: 'http://localhost:8080'
            jwt:
                enabled: false

        grails:
            serverURL: "http://localhost:8080"

        server:
            port: "8087"
        spring:
            autoconfigure:
                exclude: "au.org.ala.ws.security.AlaWsSecurityConfiguration"

---
listsFieldMappingV2:
        matchedName: "classification.scientificName"
        commonName: "classification.vernacularName"
        rawScientificName: "scientificName"